package com.revela.analysis

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlin.math.PI
import kotlin.math.sin

/**
 * Fixtures policy: negative controls are hardcoded literals that were
 * generated by seeded shuffling and VERIFIED pattern-free against a replica
 * of these detectors (naive `Random.shuffle` controls can alias into new
 * periodic structure and flake). Planted fixtures are analytic.
 */
class DetectorsTest {

    // --- Periodicity -------------------------------------------------------

    private fun weeklyCycle(days: Int): DoubleArray =
        DoubleArray(days) { t -> 100.0 + 40.0 * sin(2 * PI * t / 7.0) + (t % 3) }

    @Test
    fun `planted 7-day cycle is detected`() {
        val result = Periodicity.detect(weeklyCycle(60))
        assertNotNull(result)
        assertEquals(7, result!!.periodDays)
        assertTrue("strength should be strong, was ${result.strength}", result.strength > 0.5)
        assertTrue(result.cycles >= 8)
    }

    @Test
    fun `shuffled control has no period`() {
        assertNull(Periodicity.detect(SHUFFLED_CYCLE_60))
    }

    @Test
    fun `constant series has no period`() {
        assertNull(Periodicity.detect(DoubleArray(60) { 100.0 }))
    }

    @Test
    fun `too-short series is not judged`() {
        assertNull(Periodicity.detect(weeklyCycle(14)))
    }

    @Test
    fun `steady noise has no period`() {
        assertNull(Periodicity.detect(STEADY_NOISE_60))
    }

    // --- Change point ------------------------------------------------------

    @Test
    fun `level shift is located with correct means`() {
        val values = DoubleArray(60) { t -> if (t < 30) 100.0 + (t % 5) else 200.0 + (t % 5) }
        val result = ChangePoint.detect(values)
        assertNotNull(result)
        assertTrue("index ${result!!.index} should be near 30", result.index in 28..32)
        assertTrue(result.beforeMean in 95.0..110.0)
        assertTrue(result.afterMean in 195.0..210.0)
    }

    @Test
    fun `steady noise has no change point`() {
        assertNull(ChangePoint.detect(STEADY_NOISE_60))
    }

    @Test
    fun `weekly cycle alone is not mistaken for a shift`() {
        assertNull(ChangePoint.detect(weeklyCycle(60)))
    }

    // --- Deviation ---------------------------------------------------------

    @Test
    fun `triple the normal value is flagged high`() {
        val history = DoubleArray(20) { 100.0 + (it % 7) }
        val result = Deviation.detect(history, 300.0)
        assertNotNull(result)
        assertEquals(Deviation.Direction.HIGH, result!!.direction)
        assertTrue(result.robustZ > 2.0)
    }

    @Test
    fun `a normal value is not flagged`() {
        val history = DoubleArray(20) { 100.0 + (it % 7) }
        assertNull(Deviation.detect(history, 104.0))
    }

    @Test
    fun `thin history is not judged`() {
        assertNull(Deviation.detect(doubleArrayOf(100.0, 110.0, 90.0), 300.0))
    }

    // --- Chronotype --------------------------------------------------------

    @Test
    fun `weekend shift of an hour is reported`() {
        val weekday = DoubleArray(10) { 420.0 + (it % 3) * 5 } // ~07:00
        val weekend = DoubleArray(4) { 480.0 + (it % 2) * 5 }  // ~08:00
        val result = Chronotype.detect(weekday, weekend)
        assertNotNull(result)
        assertTrue("shift was ${result!!.shiftMin}", result.shiftMin in 50.0..70.0)
    }

    @Test
    fun `small shift stays quiet`() {
        val weekday = DoubleArray(10) { 420.0 }
        val weekend = DoubleArray(4) { 430.0 }
        assertNull(Chronotype.detect(weekday, weekend))
    }
}

// Verified-silent permutation of weeklyCycle(60).
internal val SHUFFLED_CYCLE_60 = doubleArrayOf(
    101.0, 82.64, 82.64, 62.0, 140.0, 102.0, 83.64, 140.0,
    61.0, 101.0, 140.0, 61.0, 83.64, 117.36, 68.73, 69.73,
    63.0, 118.36, 131.27, 119.36, 119.36, 141.0, 132.27, 83.64,
    84.64, 118.36, 70.73, 139.0, 100.0, 63.0, 68.73, 118.36,
    117.36, 139.0, 139.0, 133.27, 69.73, 132.27, 131.27, 141.0,
    131.27, 70.73, 61.0, 101.0, 102.0, 132.27, 100.0, 133.27,
    141.0, 68.73, 119.36, 117.36, 63.0, 84.64, 69.73, 102.0,
    84.64, 133.27, 62.0, 100.0,
)

// Verified: no period, no change point.
internal val STEADY_NOISE_60 = doubleArrayOf(
    114.62, 104.81, 112.75, 111.01, 111.95, 106.66, 107.7, 119.7,
    117.58, 118.82, 105.5, 102.58, 102.93, 100.46, 110.93, 119.29,
    102.09, 112.5, 108.22, 115.53, 119.81, 109.74, 114.92, 114.66,
    116.35, 116.78, 110.53, 117.99, 102.68, 101.66, 119.57, 114.45,
    114.3, 102.86, 109.26, 100.09, 101.43, 106.97, 106.78, 117.19,
    119.43, 117.31, 112.25, 103.58, 104.35, 117.09, 100.19, 113.85,
    115.43, 114.25, 104.22, 115.66, 118.91, 100.28, 107.88, 117.08,
    115.72, 119.87, 117.66, 103.41,
)
